version: '3.8'

services:
  
  postgres:
    image: weebdevowo/docker_node_app:postgres
    build: ./postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - vol-postgres:/var/lib/postgresql/data

  node_rest_api:
    depends_on: 
      - postgres
    image: weebdevowo/docker_node_app:node_rest_api
    build: ./node_rest_api
    ports: 
      - "5001:8080"
    environment:
      PORT: ${PORT}
      POSTGRESS_HOST: ${POSTGRESS_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./node_rest_api/src/:/usr/app/src/ #(COMMENT OUT FOR PRODUCTION) for development only to use nodemon


volumes:
  vol-postgres:
    driver: local