version: '3.8'

services:

  db:
    build: ./db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - vol-db:/var/lib/postgresql/data

  web:
    depends_on: 
      - db
    build: ./node_dock
    ports: 
      - "5001:8080"
    environment:
      PORT: ${PORT}
      POSTGRESS_HOST: ${POSTGRESS_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./node_dock/:/usr/app/ #(COMMENT OUT FOR PRODUCTION) for development only to use nodemon
      - ignore:/usr/app/node_modules/ #(COMMENT OUT FOR PRODUCTION) for development only to use nodemon


volumes:
  ignore: #(COMMENT OUT FOR PRODUCTION) for development only to use nodemon
  vol-db:
    driver: local