name: Docker Compose Actions Workflow (build and push to docker hub)
on: push
jobs:
  build_then_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: build image (docker compose build)
        run: docker compose build --no-cache
      
      - name: push to docker hub
        run: docker push ${{secrets.DOCKER_USER}}/docker_node_app


#xd